### Gauss-Jordan SPL 3 Variabel (x,y,z)

In [7]:
import numpy as np
import re
from sympy import symbols, Eq, sympify

def parse_equations(equations):
    variables = set(re.findall(r'[a-zA-Z]', ' '.join(equations)))
    variables = sorted(variables)
    symbols_dict = {var: symbols(var) for var in variables}
    symbol_list = [symbols_dict[var] for var in variables]
    coefficients = []
    constants = []

    for eq in equations:
        lhs, rhs = eq.split('=')
        lhs = sympify(lhs.strip(), locals=symbols_dict)
        rhs = sympify(rhs.strip(), locals=symbols_dict)
        equation = Eq(lhs, rhs)

        coeff_row = [float(lhs.coeff(var).evalf()) for var in symbol_list]
        coefficients.append(coeff_row)

        constant = (rhs - lhs.subs({var: 0 for var in symbol_list})).evalf()
        constants.append(float(constant))

    A = np.array(coefficients, dtype=float)
    B = np.array(constants, dtype=float).flatten()

    return A, B

#### Input Equation

In [8]:
equations = [
    "2*x + 0*y + 6*z = 40",
    "0*x + 4*y - 1*z = 10",
    "2*x - 1*y + 2*z = 12",
]

# equations = [
#     "6*x + 9*y - 4*z = -6",
#     "0*x + 5*y - 3*z = 29",
#     "7*x + 0*y - 5*z = -48",
# ]

# equations = [
#     "-4*x + 6*y + 9*z = -74",
#     "2*x + 7*y - 3*z = -26",
#     "7*x - 3*y + 7*z = 39",
# ]

# print(equations)

A, B = parse_equations(equations)

print("Matriks Koefisien (A):")
print(A)
print("\nMatriks Konstanta (B):")
print(B)

matriks = np.hstack((A, B.reshape(-1, 1)))
matriks = matriks.astype(np.float64)
print("\nMatriks Augmentasi:")
print(matriks)

Matriks Koefisien (A):
[[ 2.  0.  6.]
 [ 0.  4. -1.]
 [ 2. -1.  2.]]

Matriks Konstanta (B):
[40. 10. 12.]

Matriks Augmentasi:
[[ 2.  0.  6. 40.]
 [ 0.  4. -1. 10.]
 [ 2. -1.  2. 12.]]


#### Cara Manual (per iterasi)

In [9]:
def print_iterasi(i, matriks):
    print(f"Iterasi {i}:\n")
    print(matriks)
    print("\n")
    
i = 0
satu_utama_0 = False
satu_utama_1 = False
satu_utama_2 = False

if matriks[0,0] != 0:
    matriks[0,:] = np.round(matriks[0,:] * (1/matriks[0,0]), decimals=2)
    i += 1
    satu_utama_0 = True
    print_iterasi(i, matriks)

if matriks[1,0] != 0 and satu_utama_0:
    matriks[1,:] = np.round(matriks[0,:] * (-matriks[1,0]) + matriks[1,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[2,0] != 0 and satu_utama_0:
    matriks[2,:] = np.round(matriks[0,:] * (-matriks[2,0]) + matriks[2,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[1,1] != 0:
    matriks[1,:] = np.round(matriks[1,:] * (1/matriks[1,1]), decimals=2)
    i += 1
    satu_utama_1 = True
    print_iterasi(i, matriks)

if matriks[2,1] != 0 and satu_utama_1:
    matriks[2,:] = np.round(matriks[1,:] * (-matriks[2,1]) + matriks[2,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[2,2] != 0:
    matriks[2,:] = np.round(matriks[2,:] * (1/matriks[2,2]), decimals=2)
    i += 1
    satu_utama_2 = True
    print_iterasi(i, matriks)

if matriks[1,2] != 0 and satu_utama_2:
    matriks[1,:] = np.round(matriks[2,:] * (-matriks[1,2]) + matriks[1,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[0,2] != 0 and satu_utama_2:
    matriks[0,:] = np.round(matriks[2,:] * (-matriks[0,2]) + matriks[0,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[0,1] != 0 and satu_utama_1:
    matriks[0,:] = np.round(matriks[1,:] * (-matriks[0,1]) + matriks[0,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

Iterasi 1:

[[ 1.  0.  3. 20.]
 [ 0.  4. -1. 10.]
 [ 2. -1.  2. 12.]]


Iterasi 2:

[[  1.   0.   3.  20.]
 [  0.   4.  -1.  10.]
 [  0.  -1.  -4. -28.]]


Iterasi 3:

[[  1.     0.     3.    20.  ]
 [  0.     1.    -0.25   2.5 ]
 [  0.    -1.    -4.   -28.  ]]


Iterasi 4:

[[  1.     0.     3.    20.  ]
 [  0.     1.    -0.25   2.5 ]
 [  0.     0.    -4.25 -25.5 ]]


Iterasi 5:

[[ 1.    0.    3.   20.  ]
 [ 0.    1.   -0.25  2.5 ]
 [-0.   -0.    1.    6.  ]]


Iterasi 6:

[[ 1.  0.  3. 20.]
 [ 0.  1.  0.  4.]
 [-0. -0.  1.  6.]]


Iterasi 7:

[[ 1.  0.  0.  2.]
 [ 0.  1.  0.  4.]
 [-0. -0.  1.  6.]]




#### Cara Otomatis (library linalg)

In [10]:
matriks_auto = np.linalg.solve(A, B)
matriks_auto

array([2., 4., 6.])

### Matriks Ukuran Lain

In [11]:
import numpy as np
from decimal import Decimal, ROUND_HALF_UP

round_half_up = lambda x, d=0: np.vectorize(lambda n: float(Decimal(str(n)).quantize(Decimal('1.' + '0'*d), rounding=ROUND_HALF_UP)))(x)

def round(n, decimals=0):
    d = Decimal(str(n))
    return float(d.quantize(Decimal('1.' + '0' * decimals), rounding=ROUND_HALF_UP))

def print_iterasi(i, matriks):
    # print(f"Iterasi {i}:\n")
    for row in matriks:
        print("  ".join(f"{val:8.2f}" for val in row))
    print("\n")

    
def gauss_jordan(matriks, decimals=2):
    matriks = matriks.astype(float).copy()
    n, m = matriks.shape
    iter_no = 0

    print(f"n:{n}")
    for i in range(n):
        iter_no += 1
        pivot = matriks[i,i]
        matriks[i] = np.round(matriks[i] / pivot, 2)
        print(f"Iterasi {iter_no} (baris {i+1} = baris {i+1} / {pivot}):")
        print_iterasi(i, matriks)
        
        for j in range(i+1, n):
            factor = matriks[j, i]
            if factor != 0:
                iter_no += 1
                matriks[j] = np.round(matriks[j] - factor * matriks[i], 2)
                print(f"Iterasi {iter_no} (baris {j+1} = baris {i+1} * {-1 * factor:.2f} + baris {j+1}:")
                print_iterasi(i, matriks)
        
    for i in range(n-1, -1, -1):
        for j in range(i-1, -1, -1):                
            factor = matriks[j, i]
            if factor != 0:
                iter_no += 1
                matriks[j] = np.round(matriks[j] - factor * matriks[i], 2)
                print(f"Iterasi {iter_no} (baris {j+1} = baris {i+1} * {-1 * factor:.2f} + baris {j+1}:")
                print_iterasi(i, matriks)
    
    return matriks

# Input Matriks

matriks = np.array([
    [3, 2, -1, 4, 5, 12],
    [2, -3, 4, -1, 5, 5],
    [1, 4, -2, 3, 1, 8]
], dtype=float)

# matriks = np.array([
#     [7, 3, 6, -5, 4, -5],
#     [-4, 6, 2, 6, 7, 4],
#     [3, 8, 3, -4, 5, 2],
#     [2, -4, 7, 9, -4, 6]
# ], dtype=float)

# matriks = np.array([
#     [6, 3, -3, 2, 3, -6],
#     [4, -6, 8, 3, 9, 3],
#     [5, -7, 6, 7, -5, 2],
#     [-8, 9, -3, 4, 2, 7]
# ], dtype=float)


hasil = gauss_jordan(matriks, decimals=2)

print("Hasil Akhir Matriks:")
print(hasil)


n:3
Iterasi 1 (baris 1 = baris 1 / 3.0):
    1.00      0.67     -0.33      1.33      1.67      4.00
    2.00     -3.00      4.00     -1.00      5.00      5.00
    1.00      4.00     -2.00      3.00      1.00      8.00


Iterasi 2 (baris 2 = baris 1 * -2.00 + baris 2:
    1.00      0.67     -0.33      1.33      1.67      4.00
    0.00     -4.34      4.66     -3.66      1.66     -3.00
    1.00      4.00     -2.00      3.00      1.00      8.00


Iterasi 3 (baris 3 = baris 1 * -1.00 + baris 3:
    1.00      0.67     -0.33      1.33      1.67      4.00
    0.00     -4.34      4.66     -3.66      1.66     -3.00
    0.00      3.33     -1.67      1.67     -0.67      4.00


Iterasi 4 (baris 2 = baris 2 / -4.34):
    1.00      0.67     -0.33      1.33      1.67      4.00
   -0.00      1.00     -1.07      0.84     -0.38      0.69
    0.00      3.33     -1.67      1.67     -0.67      4.00


Iterasi 5 (baris 3 = baris 2 * -3.33 + baris 3:
    1.00      0.67     -0.33      1.33      1.67      4.00
 

In [12]:
import numpy as np

def print_iterasi(iter_no, matriks):
    print(f"Iterasi {iter_no}:")
    for row in matriks:
        print("  ".join(f"{val:8.2f}" for val in row))
    print("\n")

def gauss_jordan(matriks, decimals=2):
    matriks = matriks.astype(float).copy()
    n, m = matriks.shape
    iter_no = 0
    
    for col in range(n):
        if abs(matriks[col, col]) < 1e-12:
            for r in range(col+1, n):
                if abs(matriks[r, col]) > 1e-12:
                    matriks[[col, r]] = matriks[[r, col]]
                    break

        pivot = matriks[col, col]
        if abs(pivot) < 1e-12:
            continue

        matriks[col, :] = np.round(matriks[col, :] / pivot, decimals=decimals)
        iter_no += 1
        print_iterasi(iter_no, matriks)

        for r in range(col+1, n):
            if abs(matriks[r, col]) > 1e-12:
                factor = matriks[r, col]
                matriks[r, :] = np.round(matriks[r, :] - factor * matriks[col, :], decimals=decimals)
                iter_no += 1
                print_iterasi(iter_no, matriks)
                
    for col in range(n-1, -1, -1):
        for r in range(col-1, -1, -1):
            if abs(matriks[r, col]) > 1e-12:
                factor = matriks[r, col]
                matriks[r, :] = np.round(matriks[r, :] - factor * matriks[col, :], decimals=decimals)
                iter_no += 1
                print_iterasi(iter_no, matriks)

    return matriks

matriks = np.array([
    [6, 3, 2, 7, -6, -3],
    [2, -6, 9, -4, 3, 6],
    [3, -7, -5, 3, 7, 8],
    [7, 9, 2, 5, 4, 4]
], dtype=float)

hasil = gauss_jordan(matriks, decimals=2)

print("Hasil Akhir Matriks:")
print(hasil)


Iterasi 1:
    1.00      0.50      0.33      1.17     -1.00     -0.50
    2.00     -6.00      9.00     -4.00      3.00      6.00
    3.00     -7.00     -5.00      3.00      7.00      8.00
    7.00      9.00      2.00      5.00      4.00      4.00


Iterasi 2:
    1.00      0.50      0.33      1.17     -1.00     -0.50
    0.00     -7.00      8.34     -6.34      5.00      7.00
    3.00     -7.00     -5.00      3.00      7.00      8.00
    7.00      9.00      2.00      5.00      4.00      4.00


Iterasi 3:
    1.00      0.50      0.33      1.17     -1.00     -0.50
    0.00     -7.00      8.34     -6.34      5.00      7.00
    0.00     -8.50     -5.99     -0.51     10.00      9.50
    7.00      9.00      2.00      5.00      4.00      4.00


Iterasi 4:
    1.00      0.50      0.33      1.17     -1.00     -0.50
    0.00     -7.00      8.34     -6.34      5.00      7.00
    0.00     -8.50     -5.99     -0.51     10.00      9.50
    0.00      5.50     -0.31     -3.19     11.00      7.50


Iter