### Gauss-Jordan SPL 3 Variabel (x,y,z)

In [ ]:
import numpy as np
import re
from sympy import symbols, Eq, sympify

def parse_equations(equations):
    variables = set(re.findall(r'[a-zA-Z]', ' '.join(equations)))
    variables = sorted(variables)
    symbols_dict = {var: symbols(var) for var in variables}
    symbol_list = [symbols_dict[var] for var in variables]
    coefficients = []
    constants = []

    for eq in equations:
        lhs, rhs = eq.split('=')
        lhs = sympify(lhs.strip(), locals=symbols_dict)
        rhs = sympify(rhs.strip(), locals=symbols_dict)
        equation = Eq(lhs, rhs)

        coeff_row = [float(lhs.coeff(var).evalf()) for var in symbol_list]
        coefficients.append(coeff_row)

        constant = (rhs - lhs.subs({var: 0 for var in symbol_list})).evalf()
        constants.append(float(constant))

    A = np.array(coefficients, dtype=float)
    B = np.array(constants, dtype=float).flatten()

    return A, B

#### Input Equation

In [ ]:
equations = [
    "2*x + 3*y - 1*z = -14",
    "1*x - 1*y - 2*z = -6",
    "-2*x + 1*y + 2*z = 4",
]

A, B = parse_equations(equations)

print("Matriks Koefisien (A):")
print(A)
print("\nMatriks Konstanta (B):")
print(B)

matriks = np.hstack((A, B.reshape(-1, 1)))
matriks = matriks.astype(np.float64)
print("\nMatriks Augmentasi:")
print(matriks)

#### Cara Manual (per iterasi)

In [ ]:
def print_iterasi(i, matriks):
    print(f"Iterasi {i}:\n")
    print(matriks)
    print("\n")
    
i = 0
satu_utama_0 = False
satu_utama_1 = False
satu_utama_2 = False

if matriks[0,0] != 0:
    matriks[0,:] = np.round(matriks[0,:] * (1/matriks[0,0]), decimals=2)
    i += 1
    satu_utama_0 = True
    print_iterasi(i, matriks)

if matriks[1,0] != 0 and satu_utama_0:
    matriks[1,:] = np.round(matriks[0,:] * (-matriks[1,0]) + matriks[1,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[2,0] != 0 and satu_utama_0:
    matriks[2,:] = np.round(matriks[0,:] * (-matriks[2,0]) + matriks[2,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[1,1] != 0:
    matriks[1,:] = np.round(matriks[1,:] * (1/matriks[1,1]), decimals=2)
    i += 1
    satu_utama_1 = True
    print_iterasi(i, matriks)

if matriks[2,1] != 0 and satu_utama_1:
    matriks[2,:] = np.round(matriks[1,:] * (-matriks[2,1]) + matriks[2,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[2,2] != 0:
    matriks[2,:] = np.round(matriks[2,:] * (1/matriks[2,2]), decimals=2)
    i += 1
    satu_utama_2 = True
    print_iterasi(i, matriks)

if matriks[1,2] != 0 and satu_utama_2:
    matriks[1,:] = np.round(matriks[2,:] * (-matriks[1,2]) + matriks[1,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[0,2] != 0 and satu_utama_2:
    matriks[0,:] = np.round(matriks[2,:] * (-matriks[0,2]) + matriks[0,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

if matriks[0,1] != 0 and satu_utama_1:
    matriks[0,:] = np.round(matriks[1,:] * (-matriks[0,1]) + matriks[0,:], decimals=2)
    i += 1
    print_iterasi(i, matriks)

#### Cara Otomatis (library linalg)

In [ ]:
matriks_auto = np.linalg.solve(A, B)
matriks_auto

### Matriks Ukuran Lain

In [ ]:
import numpy as np

def print_iterasi(i, matriks):
    print(f"Iterasi {i}:\n")
    # print(np.round(matriks, 2))
    print(matriks)
    print("\n")

def gauss_jordan(matriks, decimals=2):
    matriks = matriks.astype(float).copy()
    n, m = matriks.shape
    i = 0

    for col in range(n):
        # cek ada pivot yang 0 apa gak, kalau ada tuker
        if abs(matriks[col, col]) < 1e-12:
            for r in range(col+1, n):
                if abs(matriks[r, col]) > 1e-12:
                    matriks[[col, r]] = matriks[[r, col]]
                    break

        if abs(matriks[col, col]) > 1e-12:
            matriks[col, :] = np.round(matriks[col, :] / matriks[col, col], decimals=decimals)
            i += 1
            print_iterasi(i, matriks)
            
            for r in range(n):
                if r != col and abs(matriks[r, col]) > 1e-12:
                    matriks[r, :] = np.round(matriks[r, :] - matriks[col, :] * matriks[r, col], decimals=decimals)
                    i += 1
                    print_iterasi(i, matriks)

    return matriks

# Input Matriks
matriks = np.array([
    [3, 3, -2, 7, 2, -47],
    [2, 5, -5, -2, 4, 8],
    [-4, 8, 5, 10, -3, -21],
    [2, 6, 6, 8, 4, -6]
], dtype=float)

hasil = gauss_jordan(matriks, decimals=2)

print("Hasil Akhir Matriks:")
print(hasil)


Iterasi 1:

[[  1.     1.    -0.67   2.33   0.67 -15.67]
 [  2.     5.    -5.    -2.     4.     8.  ]
 [ -4.     8.     5.    10.    -3.   -21.  ]
 [  2.     6.     6.     8.     4.    -6.  ]]


Iterasi 2:

[[  1.     1.    -0.67   2.33   0.67 -15.67]
 [  0.     3.    -3.66  -6.66   2.66  39.34]
 [ -4.     8.     5.    10.    -3.   -21.  ]
 [  2.     6.     6.     8.     4.    -6.  ]]


Iterasi 3:

[[  1.     1.    -0.67   2.33   0.67 -15.67]
 [  0.     3.    -3.66  -6.66   2.66  39.34]
 [  0.    12.     2.32  19.32  -0.32 -83.68]
 [  2.     6.     6.     8.     4.    -6.  ]]


Iterasi 4:

[[  1.     1.    -0.67   2.33   0.67 -15.67]
 [  0.     3.    -3.66  -6.66   2.66  39.34]
 [  0.    12.     2.32  19.32  -0.32 -83.68]
 [  0.     4.     7.34   3.34   2.66  25.34]]


Iterasi 5:

[[  1.     1.    -0.67   2.33   0.67 -15.67]
 [  0.     1.    -1.22  -2.22   0.89  13.11]
 [  0.    12.     2.32  19.32  -0.32 -83.68]
 [  0.     4.     7.34   3.34   2.66  25.34]]


Iterasi 6:

[[  1.     0.